full_stack/portfolio_rails/config/routes.rb
Rails.application.routes.draw do
  root to: 'initiatives#index'

  resource :sessions
  resources :initiatives
end

full_stack/portfolio_rails/app/models/account.rb
class Account < ApplicationRecord
  has_many :assignments
  has_many :users, through: :assignments
  has_many :roles, through: :assignments
  has_many :initiatives

  validates :name, presence: true, uniqueness: true
  validates :subdomain, presence: true, uniqueness: true
end

full_stack/portfolio_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

full_stack/portfolio_rails/app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :account
  belongs_to :user
  belongs_to :role
end

full_stack/portfolio_rails/app/models/initiative.rb
class Initiative < ApplicationRecord
  belongs_to :account

  validates :title, presence: true, uniqueness: {scope: :account_id}
  validates :description, length: {maximum: 500}
  validates :time_period, presence: true
  validates :population, presence: true
  validates :employee_num, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :countries, presence: true
  validates :language, presence: true
  validates :account_id, presence: true
end

full_stack/portfolio_rails/app/models/role.rb
class Role < ApplicationRecord
  has_many :assignments
  has_many :users, through: :assignments
  has_many :accounts, through: :assignments

  validates :name, presence: true, uniqueness: true
  validates :title, presence: true, uniqueness: true

  ROLES = %w(admin user).freeze

  def self.set_up
    ROLES.each { |r| Role.create(name: r, title: r.capitalize) }
  end

  ROLES.each do |role|
    define_singleton_method(role) { Role.find_by(name: role) }

    define_method("#{role}?") { name == role }
  end
end

full_stack/portfolio_rails/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :assignments
  has_many :accounts, through: :assignments
  has_many :roles, through: :assignments

  validates :email, presence: true, uniqueness: true
end

full_stack/portfolio_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success

  before_action :authenticate!

  def curr_user
    @current_user ||= User.find(decoded_auth_token[:user_id])
  end

  def curr_account
    @current_account ||= Account.find(decoded_auth_token[:account_id])
  end

  def signed_in?
    @current_user.present?
  end

  private

  def account_subdomain
    request.subdomain.split('.').first
  end

  def authenticate!
    begin
      decoded_auth_token
      curr_user
      curr_account
    rescue JWT::ExpiredSignature, JWT::VerificationError
      reset_session
    end
  end

  def decoded_auth_token
    raise JWT::VerificationError if cookies.permanent[:token].blank?
    @decoded_auth_token ||= JsonWebToken.decode(cookies.permanent[:token])
  end

  def reset_session
    cookies.permanent[:token] = nil

    redirect_to :new_sessions
  end

  helper_method :curr_user, :curr_account, :signed_in?
end

full_stack/portfolio_rails/app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  def index
    render locals: {initiatives: curr_account.initiatives}
  end

  def show
    render locals: {initiative: curr_account.initiatives.find(params[:id])}
  end
end

full_stack/portfolio_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate!, only: [:new, :create]

  def new
  end

  def create
    account = Account.find_by(subdomain: account_subdomain)
    handle_invalid_credentials && return if account.blank?

    user = account.users.find_by(email: session_params[:email])
    handle_invalid_credentials && return if user.blank?

    if user.authenticate(session_params[:password])
      cookies.permanent[:token] = JsonWebToken.encode({account_id: account.id,
                                                       user_id:    user.id})

      redirect_to root_path
    else
      handle_invalid_credentials
    end
  end

  def destroy
    reset_session
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

  def handle_invalid_credentials
    flash.now[:error] = 'Invalid email or password'
    render :new
  end
end

full_stack/portfolio_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

full_stack/portfolio_rails/app/views/initiatives/index.slim
h3 Initiatives

table.table.table-striped.table-hover
  thead
    tr
      th Title
      th Time Period
      th Target Population
      th Employee Number
      th Target Countries
      th Language
      th Launch Date
  tbody
    - initiatives.each do |i|
      tr
        td = link_to i.title, initiative_path(i)
        td = i.time_period
        td = i.population
        td = i.employee_num
        td = i.countries.gsub(',', ', ')
        td = i.language
        td = i.launch_date

full_stack/portfolio_rails/app/views/initiatives/show.slim
div.row
  div.panel.panel-primary
    div.panel-heading
      h3.panel-title Initiative Info

    div.panel-body
      div
        strong Title:&nbsp;
        span = initiative.title
      div
        strong Time Period:&nbsp;
        span = initiative.time_period
      div
        strong Population:&nbsp;
        span = initiative.population
      div
        strong Target Employee Number:&nbsp;
        span = initiative.employee_num
      div
        strong Countries:&nbsp;
        span = initiative.countries.gsub(',', ', ')
      div
        strong Language:&nbsp;
        span = initiative.language
      div
        strong Launch Date:&nbsp;
        span = initiative.launch_date.strftime('%m/%d/%Y')
      br
      div
        = link_to 'All Initiatives', initiatives_path, class: 'btn btn-primary'

full_stack/portfolio_rails/app/views/layouts/_footer.slim
nav.navbar.navbar-default.navbar-fixed-bottom
  h6.navbar-text Powered by Sen

full_stack/portfolio_rails/app/views/layouts/_header.slim
nav.navbar.navbar-inverse
  div.container-fluid
    div.navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle="collapse" data-target="#navbar_collapse"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Portfolio', root_path, class: 'navbar-brand'

    - if signed_in?
      div#navbar_collapse.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          li = link_to 'Settings', root_path
          li = link_to 'Support', root_path
          li.dropdown
            = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
              | Hi #{curr_user.first_name || 'User'}!
              span.caret
            ul.dropdown-menu
              li = link_to 'Logout', sessions_path, method: :delete

full_stack/portfolio_rails/app/views/layouts/application.slim
doctype html
html
  head
    title Portfolio Rails
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = render partial: 'layouts/header'
    div.container.container-fluid
      = yield
    = render partial: 'layouts/footer'

full_stack/portfolio_rails/app/views/shared/_flash_msg.slim
- if flash[:success].present?
  div.alert.alert-success
    = flash[:success]

- if flash[:info].present?
  div.alert.alert-info
    = flash[:info]

- if flash[:warning].present?
  div.alert.alert-warning
    = flash[:warning]

- if flash[:error].present?
  div.alert.alert-danger
    = flash[:error]